"""
related_issues.py — when the engine's own confidence in a match is
borderline, suggest 2-3 other plausible root causes for the SAME reported
symptom, instead of only ever presenting the single best guess as if it
were certain.

Why this exists: a black screen can genuinely be a software glitch, a
completely drained battery, or a display hardware fault -- three different
root causes that look identical to the user but need different fixes. When
the engine's own match confidence is high, it has effectively already
picked the most likely one and a caveat would just add noise. But when
confidence is borderline (this codebase already tracks that -- see
escalation.py), silently presenting one plan with no acknowledgment that
other explanations exist overstates the engine's certainty. This module
closes that gap.

Design, deliberately narrow and honest (same philosophy as safety.py and
clarify.py):
  - Reuses pipeline.py's EXISTING escalation signal (a Goal carrying
    `escalation`) as the "is this borderline?" trigger, rather than
    inventing a new confidence threshold -- both execution paths already
    decide this for themselves using whichever confidence signal they
    actually have (see escalation.py's module docstring), so this module
    never has to re-derive it.
  - Reuses pipeline.py's EXISTING `_guess_issue_phrase()` symptom buckets
    (the same ~17 buckets that already power the /stats trending-issues
    breakdown) as the lookup key, rather than a second classifier.
  - A hand-curated map from symptom bucket -> 2-3 plausible alternative
    root causes. This is intentionally NOT generated by an LLM call: it's
    the same kind of small, reviewable, zero-cost, zero-latency knowledge
    this codebase already leans on elsewhere (builtin_knowledge.py,
    safety.py's hazard patterns) rather than one more moving part that
    could hallucinate or add a network round trip on the hot path.
  - A bucket with no curated entry returns [] rather than guessing --
    exactly the same "never invent, degrade honestly" rule the rest of
    this codebase follows.
"""
from __future__ import annotations

# Keyed on pipeline.py's _guess_issue_phrase() bucket labels (verbatim) so
# this can never silently drift out of sync with what /stats already
# reports as the symptom for a given complaint.
_RELATED_CAUSES: dict[str, list[str]] = {
    "Battery draining fast": [
        "A specific app running heavily in the background",
        "A software bug introduced by a recent update",
        "Normal battery wear on an older device",
    ],
    "Battery not charging": [
        "A damaged cable or adapter rather than the phone itself",
        "A blocked or damaged charging port",
        "A charging-port hardware fault",
    ],
    "Camera blurry / out of focus": [
        "A dirty or obstructed lens",
        "A case or screen protector partially covering the lens",
        "An autofocus hardware fault",
    ],
    "Camera app crashing": [
        "A corrupted Camera app cache",
        "Low device storage",
        "An outdated Camera app version",
    ],
    "Wi-Fi connectivity": [
        "The router or network itself, not the phone",
        "A corrupted saved network profile",
        "Outdated software",
    ],
    "Bluetooth connectivity": [
        "An issue with the OTHER paired device, not this one",
        "Outdated software",
        "A Bluetooth radio hardware fault",
    ],
    "Device overheating": [
        "A specific app overusing the processor",
        "Charging the device while under heavy use",
        "Battery hardware wear generating extra heat",
    ],
    "Screen flickering": [
        "A display hardware fault",
        "A software/display-driver bug from a recent update",
        "A third-party app conflicting with the display",
    ],
    "Screen cracked / physical damage": [
        "Touch digitizer damage beneath the crack, not just the glass",
        "A loose internal display connector from the impact",
    ],
    "Black / blank screen": [
        "A software freeze or crash rather than a hardware fault",
        "A completely drained battery with no charge indicator showing",
        "A display hardware fault",
    ],
    "Touchscreen unresponsive": [
        "A low-quality screen protector interfering with touch sensitivity",
        "A software freeze",
        "A digitizer hardware fault",
    ],
    "Storage full": [
        "Large cached media rather than app data itself",
        "Duplicate cloud backups synced locally",
        "One specific app silently consuming excess storage",
    ],
    "App crashing": [
        "A corrupted cache for that specific app",
        "Low device storage overall",
        "An outdated version of that app",
    ],
    "Software update issue": [
        "An unstable or interrupted internet connection during download",
        "Insufficient free storage to install the update",
        "Insufficient battery charge to start the update",
    ],
    "Device running slow": [
        "Storage nearly full",
        "Too many apps running in the background",
        "Outdated software overall",
    ],
    "Speaker / audio issue": [
        "A case or debris physically covering the speaker grille",
        "A muted or Do Not Disturb setting rather than a hardware fault",
        "A speaker hardware fault",
    ],
    "Microphone issue": [
        "A specific app missing microphone permission",
        "Debris physically covering the microphone opening",
        "A microphone hardware fault",
    ],
    "Network / signal issue": [
        "A carrier network outage rather than the phone",
        "A SIM card seating issue",
        "Outdated software",
    ],
}


def suggest_related_issues(issue_phrase: str) -> list[str]:
    """Returns up to 3 alternative plausible root causes for the given
    symptom bucket (as produced by pipeline.py's `_guess_issue_phrase()`),
    or [] when there's no curated entry for it -- never guesses."""
    return list(_RELATED_CAUSES.get(issue_phrase, []))
