"""
topic_manager.py — DiagGPT-inspired session topic-stack tracking (session
memory that spans multiple complaints, not just one request).

Paper this is inspired by: "DiagGPT: An LLM-based and Multi-agent Dialogue
System with Automatic Topic Management for Flexible Task-Oriented Dialogue".
DiagGPT's central idea is a Topic Manager that maintains a stack of
conversation topics and, on each turn, decides whether to stay on the
current topic, open a new one, or jump back to a previous one -- so a
multi-turn conversation can flow the way a real support conversation does
("my battery's draining fast" ... a few turns later ... "actually, my wifi
keeps dropping too" ... later still ... "ok back to the battery thing")
instead of only ever handling one isolated complaint at a time.

Why this is a deterministic, bucket-based simplification of DiagGPT's own
LLM-driven Topic Manager rather than a literal port: DiagGPT uses a full
LLM agent (with its own prompt, action list, and reasoning step) purely to
decide "stay / new topic / jump to existing topic" for every single turn.
That's a real, recurring per-request LLM call this codebase's own
philosophy pushes hard against elsewhere -- see related_issues.py's module
docstring ("intentionally NOT generated by an LLM call ... zero-cost,
zero-latency ... rather than one more moving part that could hallucinate")
and safety.py/clarify.py's same stance. This module reuses pipeline.py's
EXISTING `_guess_issue_phrase()` symptom buckets (the same ~17 buckets that
already power /stats' trending-issues breakdown and related_issues.py) as
the topic identity signal instead: two complaints land on the "same topic"
when they land on the same bucket, which is deterministic, free, and
already computed on every request anyway.

Design, same opt-in/no-op-by-default shape as session_memory.py (Task 36):
  - Entirely keyed on the caller-supplied `session_id` (schema.py's
    existing opt-in field, already used by session_memory.py and
    resolution.py). No session_id -> update_topic_stack() returns None and
    this module is a complete no-op, byte-identical to before it existed.
  - Simplified to DiagGPT's three core actions (its own paper calls these
    the ones that "cover most topic change scenarios"): stay_at_current_topic
    (the new complaint's bucket matches the top of the stack), jump_to_
    existing_topic (matches a bucket already further down the stack -- the
    user came back to something they mentioned earlier), create_a_new_topic
    (a genuinely new bucket -- pushed on top). DiagGPT's remaining actions
    (finish_the_current_topic, load_topics_from_a_predefined_task, etc.)
    are either implicit here (an old topic just sinks down the stack rather
    than being explicitly "finished") or not applicable (there's no
    predefined per-domain checklist in this project the way DiagGPT's
    demo scenarios have).
  - Purely additive, surfaced only as `meta.topic_stack` -- never changes
    `response.contexts` or which plan is returned. Exactly the same
    "session-scoped, informational only" contract session_memory.py's
    avoidance data has for the deeplink CHOICE, except this is about which
    TOPIC the conversation is on, not which deeplink to avoid.
  - Persisted the same simple JSON-file way as session_memory.py/feedback.py
    -- no database needed for a hackathon-scale demo.
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Optional

TOPIC_STACK_PATH = Path("session_topic_stack.json")

# DiagGPT itself notes it auto-removes topics that go too long unrecalled;
# this project takes the simpler route of just bounding stack depth, which
# has the same practical effect (an old, never-revisited topic eventually
# falls off) without needing a separate expiry/staleness pass.
MAX_STACK_DEPTH = 5

_cache: dict[str, list[dict]] | None = None


def _load() -> dict[str, list[dict]]:
    global _cache
    if _cache is not None:
        return _cache
    if TOPIC_STACK_PATH.exists():
        try:
            _cache = json.loads(TOPIC_STACK_PATH.read_text())
        except Exception:
            _cache = {}
    else:
        _cache = {}
    return _cache


def _save() -> None:
    if _cache is not None:
        TOPIC_STACK_PATH.write_text(json.dumps(_cache, indent=2))


def update_topic_stack(session_id: Optional[str], issue_phrase: str) -> Optional[dict]:
    """Call once per request, after `issue_phrase` (pipeline.py's
    `_guess_issue_phrase(technical_query)` bucket label) is known. Returns
    None for no session_id (opt-in no-op, see module docstring), otherwise
    {"action": "stay_at_current_topic"|"jump_to_existing_topic"|
    "create_a_new_topic", "current_topic": issue_phrase, "stack": [...]}
    where `stack` is the current topic labels, most-recent first.

    Never raises: a corrupted/missing persistence file degrades to an
    empty stack (same defensive pattern as session_memory.py's _load())."""
    if not session_id:
        return None

    store = _load()
    stack = store.setdefault(session_id, [])
    now = time.time()

    if stack and stack[0]["topic"] == issue_phrase:
        stack[0]["last_active_at"] = now
        action = "stay_at_current_topic"
    else:
        existing_idx = next((i for i, t in enumerate(stack) if t["topic"] == issue_phrase), None)
        if existing_idx is not None:
            topic = stack.pop(existing_idx)
            topic["last_active_at"] = now
            stack.insert(0, topic)
            action = "jump_to_existing_topic"
        else:
            stack.insert(0, {"topic": issue_phrase, "created_at": now, "last_active_at": now})
            action = "create_a_new_topic"

    del stack[MAX_STACK_DEPTH:]
    _save()

    return {
        "action": action,
        "current_topic": issue_phrase,
        "stack": [t["topic"] for t in stack],
    }


def get_topic_stack(session_id: Optional[str]) -> list[str]:
    """Read-only helper (used by investigator.py / tests) -- the current
    stack for a session without recording a new turn. [] for no
    session_id or an unknown session."""
    if not session_id:
        return []
    store = _load()
    return [t["topic"] for t in store.get(session_id, [])]
